### PR TITLE
correct statement about number of vive units sold

### PR DESCRIPTION
**Pull request by stevemar**
As mentioned on reddit, it looks like we goofed and stated the overall number of VR
headset sales instead of just HTC Vive sales. 

[1] https://www.reddit.com/r/Vive/comments/6ainyk/vive_sells_21_million_units_in_2016/

### CODE REVIEW

**Comment by stevemar** [comment]
I'm also OK removing the statement entirely

**Review by scottdangelo — APPROVED** [review]

**Comment by scottdangelo** [comment]
I think it's good to keep the info here, so +2 to the patch as is.

**Comment by Perefin** [comment]
Should be removed - sales numbers change all the time and it's irrelevant for the purpose of this.

**Comment by stevemar** [comment]
Ah looks like it was pulled from https://www.cnet.com/news/virtual-reality-vr-has-arrived-but-its-not-really-here-yet/

**Comment by stevemar** [comment]
It's sourced, so pending time-travel I don't see how the 2016 sales can change. john cutter suggested merging, so going to merge.

**Pull request merged**
